# -*- coding: utf-8 -*-
"""Predict_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R9F0bBNS8W4XGcK4iNzUGuUsXoquFJTY
"""

import pandas as pd
import numpy as np
import joblib


model = joblib.load("modelo_final.pkl")
model_columns = joblib.load("columnas_modelo.pkl")

df_test = pd.read_csv("DATOSPREDICTIVA.csv")

# ------------------------
# FEATURE ENGINEERING
# ------------------------

# release_year y release_month
df_test['release_date'] = pd.to_datetime(df_test['release_date'], errors='coerce')
df_test['release_year'] = df_test['release_date'].dt.year
df_test['release_month'] = df_test['release_date'].dt.month

# num_companies
df_test['num_companies'] = df_test['production_companies'].apply(
    lambda x: len(str(x).split('-')) if pd.notnull(x) else 0
)

# main_genre (primer género de la lista)
df_test['main_genre'] = df_test['genres'].apply(
    lambda x: str(x).split(",")[0].replace("[", "").replace("'", "").strip()
    if pd.notnull(x) else "Unknown"
)
features = [
    'budget',
    'runtime',
    'release_year',
    'release_month',
    'num_companies',
    'main_genre',
    'vote_average',
    'vote_count',
    'popularity'
]

X_test = df_test[features]

X_test = pd.get_dummies(X_test, drop_first=True)

X_test.columns = (
    X_test.columns
    .str.replace('[', '', regex=False)
    .str.replace(']', '', regex=False)
    .str.replace('<', '', regex=False)
    .str.replace('>', '', regex=False)
    .str.replace("'", '', regex=False)
)

X_test = X_test.astype(float)

X_test = X_test.loc[:, ~X_test.columns.duplicated()]

X_test = X_test.reindex(columns=model_columns, fill_value=0)

predictions = model.predict(X_test)
probabilities = model.predict_proba(X_test)[:,1]

output = pd.DataFrame({
    "prediction": predictions,
    "probability": probabilities
})

output.to_csv("predicciones_finales.csv", index=False)

print("Predicciones generadas correctamente.")